### ISSUE TITLE
CLI Transform Command not working

### ISSUE THREAD

**Issue by bet20ICL** [DeepWok/mase#13]
To replicate:

Train a small network
`./ch train jsc-tiny jsc --max-epochs 1`

Quantise it
`./ch transform jsc-tiny jsc --config configs/archive/test/integer.toml --load {YOUR_CKPT_DIR} --load-type -pl`

PR #12 addresses some of the issues and explains the current error output

**Comment by jianyicheng** [comment]
Fixed by https://github.com/DeepWok/mase/pull/15
