### ISSUE TITLE
graph.py fix (maybe

### ISSUE THREAD

**Issue by zniihgnexy** [DeepWok/mase#28]
[https://github.com/DeepWok/mase/commit/03a5c687f26685c89678ddd9c3ce0bea6f3e06ae](url)

i think there're some old version masegraph tuple problem. i found this when running the search script.
from Zheng Xinyi, please corret me if this change doesn't work

**Comment by Aaron-Zhao123** [comment]
I cant really see your code somehow, but i belive it is fixed in commit [8bfb024](https://github.com/DeepWok/mase/commit/8bfb02417efa95dcc39df008103d479c39cdf864)

**Comment by zniihgnexy** [comment]
thank you for checking this problem.

**Comment by Aaron-Zhao123** [comment]
Can you plz double-check on whether this solves your probelm?

**Comment by zniihgnexy** [comment]
thank you and this error is now fixed. i talked with one of the TAs and we fixed together.

**Comment by Laurie2905-JOHN** [comment]
I am now getting this error since I have pulled the new changes. I see that the changes made in [8bfb024](https://github.com/DeepWok/mase/commit/8bfb02417efa95dcc39df008103d479c39cdf864)
are no longer present.

**Comment by jianyicheng** [comment]
@Laurie2905-JOHN  Sorry, we made some mistakes when we updated the files, which caused some previous PRs missed. I have made a fixing patch here: https://github.com/DeepWok/mase/pull/41

Feel free to help fix by submitting your own PRs!
